name: zapenv
dependencies:
  - pandas=0.24.1
  - numpy=1.16.2
  - matplotlib=3.0.2
  - seaborn=0.9.0
  - psycopg2=2.8.3
  - plotly=3.10.0
  - ipykernel=5.1.3
  - pip:
    - prophet==0.1.1
    - fbprophet==0.5
